# https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository
# last_update: 2022-04-27
_extends: devops-repo-shared-configs:github-settings/renovate-preset.yml

branches:
  - name: dev
    protection:
      required_status_checks:
        contexts: ["tests"]
